# -*- coding: utf-8 -*-
"""Google Play Store Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mz8WfY3M-y-OstqT8TaOPXFK1eEqoN1y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind

df_store=pd.read_csv("googleplaystore.csv")

df_store.head()

df_store.info()

# sammary ststistics
df_store.describe()

df_store.duplicated()

#handling missing valus
df_store.dropna(inplace=True) #drop rows with missing value

#handling duplicats
df_store.drop_duplicates(inplace=True) # remove duplicat rows

df_store.duplicated().sum()
# to check there is no duplicated value

df_store.info()

df_store['Installs']=df_store['Installs'].str.replace('+','')
df_store['Installs']=df_store['Installs'].str.replace(',','')
df_store['Installs']=df_store['Installs'].astype(int)

df_store['Reviews']=df_store['Reviews'].astype(int)

df_store.info()

plt.figure(figsize=(10,6))
sns.countplot(data=df_store , x= 'Category')
plt.xlabel=('category')
plt.ylabel=("count")
plt.xticks(rotation=90)
plt.title=('Distribution of App Category')
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(data=df_store , x= 'Reviews', y='Rating')
plt.xlabel=('Number of Reviews')
plt.ylabel=("Rating")
#plt.xticks(rotation=90)
plt.title=('THE relation between Reviews and Rating')
plt.show()

plt.figure(figsize=(10,6))
sns.scatterplot(data=df_store , x= 'Category', y='Installs')
plt.xlabel=('Category')
plt.ylabel=("Installs")
plt.xticks(rotation=90)
plt.title=('THE relation Installs across Category')
plt.show()

free_apps=df_store[df_store['Type']=='free']
paid_apps=df_store[df_store['Type']=='paid']

# preforming t-test
t_stat,p_value=ttest_ind(free_apps['Rating'],paid_apps['Rating'])

if p_value <0.5 :
  print('Reject null hypothesis : There is a significant diffrent in ratings.')
else :
  print('Fail to reject null hypothesis : There is not significant diffrent in ratings. ')

plt.figure(figsize=(12,8))
sns.scatterplot(data=df_store , y= 'Rating', x='Installs', hue='Category')
plt.grid(True)
plt.ylabel=('Rating')
plt.xlabel=("number of Installs")
plt.title=("The relation between Ratings and Installs")
plt.legend(bbox_to_anchor=(1.05,1),loc=2 ,borderaxespad=0)
plt.show()

plt.figure(figsize=(10,6))
sns.lineplot(data=df_store ,x= 'Last Updated', y='Rating')
plt.xlabel=('Last Updated')
plt.xticks(rotation=90)
plt.ylabel=("Average Rating")
plt.title=("Average Rating Trend over Time")

df_store.head()

#df_store['Last Updated'] = pd.to_datetime(df_store['Last Updated'])


#df_store.set_index('Last Updated',inplace=True)


#df_store_monthly =df_store['Rating'].resample('M').mean()

plt.figure(figsize=(10,6))
sns.lineplot(data=df_store_monthly)
plt.xlabel=('Date of last Update (Monthly)')
plt.xticks(rotation=90)
plt.ylabel=("Average Rating")
plt.title=("Average Rating Trend over Time (Monthly)")
plt.show()

